<a href="https://colab.research.google.com/github/biswajit12azure/Azure-Databricks/blob/main/Azure_Data_Engineering_Day_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df = pd.read_csv(url)

df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [9]:
# 1. Rename column
df = df.rename(columns={"total_bill": "bill_amount"})

# 2. Filter rows (only bills above 20)
df_filtered = df[df["bill_amount"] > 20]

# 3. Add new calculated column (tip percentage)
df_filtered["tip_percent"] = (df_filtered["tip"] / df_filtered["bill_amount"]) * 100

df_filtered.head()

/tmp/ipykernel_1110/1075713502.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered["tip_percent"] = (df_filtered["tip"] / df_filtered["bill_amount"]) * 100

   bill_amount   tip     sex smoker  day    time  size  tip_percent
2        21.01  3.50    Male     No  Sun  Dinner     3    16.658734
3        23.68  3.31    Male     No  Sun  Dinner     2    13.978041
4        24.59  3.61  Female     No  Sun  Dinner     4    14.680765
5        25.29  4.71    Male     No  Sun  Dinner     4    18.623962
7        26.88  3.12    Male     No  Sun  Dinner     4    11.607143

In [10]:
df_filtered.to_csv("processed_tips.csv", index=False)

print("CSV saved successfully!")

CSV saved successfully!

In [11]:
from google.colab import files
files.download("processed_tips.csv")